### ISSUE TITLE
A problem with the latest update

### ISSUE THREAD

**Issue by zfwap** [iaz3/TCBot#57]
I just tried starting the new version a few times, and I get a recurring problem.
I have tried to figure it out myself, but I failed.
Whenever the .exe is opened, a window pops up for less than a second, and vanishes.
Sorry for the low quality, I had to capture it via gif recorder, and exract the frame that showed some code in order to catch it.
![problem 2](https://cloud.githubusercontent.com/assets/17308242/13134266/604ddd4e-d5d2-11e5-9d02-d830778f8763.jpg)

**Comment by mgracer48** [comment]
Try running as admin

**Comment by zfwap** [comment]
That doesn't work either, I've tried it and I get the same result running
the .exe from the folder, and a blank window from the shortcut.

**Comment by iaz3** [comment]
The solution is to run it as admin.
If that doesnt work, it's something else that time.

In the latest update, i included a rudimentary debug log.

Now, the problem is that this saves wherever the bot is installed, which means since it's installed in program files, you need to be an admin to create files there.

I'll release a bugfix sometime today that will address this

**Comment by iaz3** [comment]
Fixed it in 3.0.1, yesterday.
