### ISSUE TITLE
Bot should automatically cancel trades when market flux

### ISSUE THREAD

**Issue by Reinitialized** [iaz3/TCBot#65]
I've had several cases where the bot would send in a request, then be stuck for several days because the trade request it sent through no longer matches the market's rates. The bot should automatically cancel the trades after a set amount of time, and try again using different methods.

**Comment by iaz3** [comment]
Please keep reports seperate. if you have another bug, do not shoehorn it into a feature request. Make a new report.

**Comment by iaz3** [comment]
In theory, if you wait long enough, the trade will go through. The thing with the trade currency is, it takes PATIENCE.

trades can take several days to complete, or complete instantly.

The problem is finding the right time to cancel, if ever. Right now, it makes most everyone a profit, and it's meant to be run all the time, so it doesnt really matter if they take a long time.

In addition, cancelling adds additional stress because of split trades. What if it's already traded some? Thats lost profit. In addition, canceling could make you miss out on a really good trade.

If somebody REALLY wants to cancel, it wont cause any problems to do it themselves. As of now though, i dont want to make it automatically cancel.
